import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

const poppins_init = Poppins({ 
  subsets: ["latin"],
  weight: ['400','500','700'],
  variable: '--font-poppins',
 });

export const metadata: Metadata = {
  title: "E-Commerce-Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins_init.variable} poppins`}>
        <Header />
        <main className=" max-w-[1440px] mx-auto w-full">
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
